### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by kovetskiy** [reconquest/tests.sh#1]
- [x] remove all 'export' statements
- [ ] add usage (how to run one test case)
- [x] move tests_do to "PUBLIC API {{{"
- [x] add tests_diff
- [x] move 'TEST_ID' and other global variables to start of file and add comments.
- [ ] add framework usage examples
- [x] fix trouble with dirty work tree, may be move .last-testcase to
   /tmp/md5-of-pwd
   _added removing last-testcase when tests passed_
- [x] rewrite tests_assert_{stdout,stderr}
- [x] move to **reconquest**
